#####################################################################
########################  内测环境profile  ##########################
#####################################################################
spring:
  profiles: ft

logging:
  level:
    root: INFO
    com.xncoding: DEBUG
  path: D:/logs/springboot-aop