#服务器端口
server:
  port: 8108

#数据源配置
spring:
  datasource:
    url: ${springclouddev.datasource.test.url}
    username: ${springclouddev.datasource.test.username}
    password: ${springclouddev.datasource.test.password}
