#数据源配置
server:
  port: 8103

spring:
  datasource:
    url: ${springclouddev.datasource.prod.url}
    username: ${springclouddev.datasource.prod.username}
    password: ${springclouddev.datasource.prod.password}
