spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://xx.xx.xx.xx:3306/database?useSSL=FALSE&serverTimezone=GMT%2B8
        username: root
        password: xxxxx
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    sharding:
      tables:
        table_data:
          key-generator:
            column: id
            type: SNOWFLAKE
          actual-data-nodes: ds0.table_data$->{0..4}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: table_data$->{id % 5}
