#服务器端口
server:
  port: 7007

#数据源配置
spring:
  datasource:
    url: ${springclouddev.datasource.dev.url}
    username: ${springclouddev.datasource.dev.username}
    password: ${springclouddev.datasource.dev.password}
